### ISSUE TITLE
uRockets + SignShop = Painful

### ISSUE THREAD

**Issue by JerichoDiamond** [Ullarah/uRocket#1]
Ullarah - seems to be an NBT tag on rocket boots which makes each batch of boots unique - thus a pain to sell in shops. The sign has to be taken down and redone after every restock.

**Comment by Ullarah** [comment]
Seems to be working just fine with SignShop. Make sure that you are re-stocking the same type of Rocket Boot. I created a test sign 1 Rocket Boot Level II for $1, stocked the chest, and bought all of the boots. Restocked with the same boots, could purchase the boots again.
